### PR TITLE
Resolve issues w/ setup-packaging branch

### PR DESCRIPTION
**Pull request by KD-7**
- [x] Use max line length of 80 for code only
- [x] Remove unsupported black versions

### CODE REVIEW

**Comment by KD-7** [comment]
@yuxqiu 
Please see: https://peps.python.org/pep-0008/#maximum-line-length

**Comment by yuxqiu** [comment]
> @yuxqiu Please see: https://peps.python.org/pep-0008/#maximum-line-length

So, let's follow the guideline?

**Comment by KD-7** [comment]
> > @yuxqiu Please see: https://peps.python.org/pep-0008/#maximum-line-length
> 
> So, let's follow the guideline?

72 for the docstrings and 79 for the code?

**Comment by yuxqiu** [comment]
> > > @yuxqiu Please see: https://peps.python.org/pep-0008/#maximum-line-length
> > 
> > 
> > So, let's follow the guideline?
> 
> 72 for the docstrings and 79 for the code?

Sure.

**Comment by yuxqiu** [comment]
> > > @yuxqiu Please see: https://peps.python.org/pep-0008/#maximum-line-length
> > 
> > 
> > So, let's follow the guideline?
> 
> 72 for the docstrings and 79 for the code?

`black` provides a justification for using 88. Please see https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length.

**Comment by yuxqiu** [comment]
> > > @yuxqiu Please see: https://peps.python.org/pep-0008/#maximum-line-length
> > 
> > 
> > So, let's follow the guideline?
> 
> 72 for the docstrings and 79 for the code?

Let's go with 88, because I'm worried that 79 is a bit too little (at least for the docstrings).

**Comment by KD-7** [comment]
> > > > @yuxqiu Please see: https://peps.python.org/pep-0008/#maximum-line-length
> > > 
> > > 
> > > So, let's follow the guideline?
> > 
> > 
> > 72 for the docstrings and 79 for the code?
> 
> Let's go with 88, because I'm worried that 79 is a bit too little (at least for the docstrings).

88 for both then

**Review by yuxqiu — APPROVED** [review]

**Pull request merged**
